### ISSUE TITLE
Work around rate limit issues

### ISSUE THREAD

**Issue by GeoffreyPlitt** [sferik/x-cli#56]
/Users/giro/.rvm/gems/ruby-1.9.3-p194/bin/t: Rate limit exceeded. Clients may not make more than 350 requests per hour.

How about handling this error by sleeping with exponential backoff number of seconds? Should result in resilient scripts with robust performance.

**Comment by brianfeister** [comment]
@sferik - any chance we could add an option to respond with the incomplete response so that we at least have some data to do something with? Also, would be nice to have a parameter to pass for `cursor` so that we can hit the rate limit and then wait 15 minutes and pass a cursor to resume for that particular call
